#ifndef __UNTITLED2_H__
#define __UNTITLED2_H__
#include<stdio.h>
 #include<conio.h>
 #include<stdlib.h>
 #include <string.h>
 void input();
 void writefile();
 void search();
 void output();
 void wallet();
 void autogeneratedmessage();
 #endif  /* #define __UNTITLED2_H__ */
